test_ci_cd

diff --git a/.github/workflows/python-app.yaml b/.github/workflows/python-app.yaml
--- a/.github/workflows/python-app.yaml
+++ b/.github/workflows/python-app.yaml
@@ -26,7 +26,7 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        python install pipenv
+        pip install pipenv
         pipenv install --system
     - name: Lint with flake8
       run: |
@@ -34,6 +34,6 @@ jobs:
     - name: Test with pytest
       run: |
         pytest
-    - name: Setup tmate session
-      if: success() || failure()
-      uses: mxschmitt/action-tmate@v3
+#    - name: Setup tmate session
+#      if: success() || failure()
+#      uses: mxschmitt/action-tmate@v3
